### PR TITLE
Adds unit tests for loklak API

### PR DESCRIPTION
**Pull request by sopankhosla**

### CODE REVIEW

**Comment by sudheesh001** [comment]
This looks great but just a few things, can you squash the last 3 commits 6a575d2 0a5c30f fdea21e That way the 3 commits make a whole lot more sense of being there.

Also can you update the readme with the documentation on how to run the tests for 
- XAMPP/LAMPP/WAMP Stack users.
- Command line `php` users.

**Comment by sopankhosla** [comment]
I will add the documentation for Tests ASAP

**Comment by sudheesh001** [comment]
@sopu great, This looks great, would you like me to merge this now or after the readme is updated on running the tests with both the *AMPP stack and php ?

**Comment by sopankhosla** [comment]
@sudheesh001 It would be better to merge after documentation IMO

**Comment by sudheesh001** [comment]
@sopu Cool, I'll be off for the day as of now, I can review the documentation update early in the morning. 😄

**Comment by sopankhosla** [comment]
@sudheesh001 Sorry for being away for 2 days. I was travelling back home. 
`phpunit` works the same way for both Command Line users and *AMP stack users. 
The only difference is the  installation. I have added the documentation, please see if something else is required.

**Pull request merged**
